server:
  port: 8001

mybatis:
  type-aliases-package: com.chan.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  #config-location: classpath:mybatis/mybatis-config.xml

  configuration:
    cache-enabled: true


spring:
  application:
    name: springcloud-provider-dept

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
    name: bronchan
    password: 123456

#eureka配置，注册服务到注册中心
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8001   #改变eureka的默认描述信息

#info配置
info:
  app.name: com.chan.springcloud.provider
  company.name: blog.chan.com


